### ISSUE TITLE
Enable network inspection for HttpClient

### ISSUE THREAD

**Issue by zourb** [facebook/stetho#116]
Is it possible to enable network inspection for HttpClient? thx.

**Comment by jasta** [comment]
Yes, however we provide no helpers to facilitate this.  There is a lower
level "raw" API for hooking this up yourself called NetworkEventReporter.
See stetho-okhttp/urlconnection source for clues as to how you'd wire this
up manually.

HttpClient does also have an interceptor type system similar to okhttp, but
in my experience it is much less complete and is harder to properly
generalize.  That's why we didn't pursue a stetho-httpclient helper.

**Comment by zourb** [comment]
@jasta thanks for your info and quick reply.

**Comment by lklots** [comment]
jasta, which part is harder to generalize? it seems friendlier than url connection. i'll write it if you guys would merge it into stetho. 

btw, when i was at fb i was working on this very tool, but 3 years earlier :) never finished but glad you guys did. looks great.

**Comment by wufeng0927** [comment]
thanks

**Comment by cazador4** [comment]
Hey @lklots, have you done this for us? (:

**Comment by lklots** [comment]
nope :(
