### ISSUE TITLE
getAllActivitiesHack fails on 4.1.1

### ISSUE THREAD

**Issue by longinoa** [facebook/stetho#123]
See https://gist.github.com/longinoa/047d5195bc65c21dc514 for the log.

We probably want to find out what version this hack started working on and gate  the function to that call.

Failing that we should not allow this to NPE and crash the host app.

**Comment by jasta** [comment]
Minimally, this code should never throw a runtime exception and should `if` guard any dangerous assumptions.  That can be improved easily so that the solution degrades naturally.  

That said, a proper fix would be to use a future proof strategy involving `Application.registerActivityLifecycleCallbacks` in `Stetho.initialize` and keeping this information available for all Stetho operations (Inspector and Dumpapp).

This bug has to be resolved for 1.1.0.

**Comment by rickbrew** [comment]
The oldest version this seems to work on is 4.3.

**Comment by jasta** [comment]
I think we can safely release 1.1.0 without this, but we should just stop using this trick in 1.1.1.

**Comment by rickbrew** [comment]
Agreed.
