### ISSUE TITLE
Provide an ability to ensure stetho is attached.

### ISSUE THREAD

**Issue by WalrusCow** [facebook/stetho#161]
Unfortunately, if I open Stetho after my app starts, it seems that I can't view the old requests, since they are not captured in the network tab.

I want to use Stetho right from the very first request my app makes. Is there some way to do this? The idea of setting a breakpoint at `Activity#onCreate` doesn't work - sometimes at that breakpoint Stetho does not appear to be registered with Chrome.  I have not yet tried to set a breakpoint at the first request made, because that can very depending on several circumstances (so I'd need to set several breakpoints).

**Comment by longinoa** [comment]
In order to be able to see network requests in Stetho you need to have Stetho initialized and chrome connected. The protocol between Stetho and dev tools is an event based protocol.

Even if you attach one dev tools instance to your process, perform some network requests and then attach another dev tools instance to the same process the second dev tools instance will have no network requests in it.

There are 2 ways I can think of to solve your problem:
One possibility that is to tackle this from a code point of view for debugging purposes only. Create something like a `Debug.waitForDebugger()` and put that in your `Application#onCreate`. This method would look something like this (after Stetho is initailized)

```
  private void waitForDevtoolsAttached() {
    while (!NetworkPeerManager.getOrCreateInstance(this).hasRegisteredPeers()) {
      try {
        Thread.sleep(1000);
      } catch (InterruptedException ex) {
      }
    }
  }
```

Obviously you would use this identically to how you would use `Debug#waitForDebugger()` and remove it from your code when you are not actively looking to inspect the network traffic in the beginning.


The other possibility is to develop a Dumper. This wont allow you to see it in dev tools but you would be able to do something like `./scripts/dumpapp network print`

**Comment by WalrusCow** [comment]
Being able to watch Stetho while using the app and immediately debug strange behaviour is much more convenient than dumping and examining after the fact.

Your suggestion works for debugging on start, although it still requires a breakpoint + manual click after waitForDevToolsAttached() finishes.

Is there some option to auto-open the dev tools? Thanks!

**Comment by longinoa** [comment]
It shouldn't require a breakpoint + manual click, however it does 
require adding the call, I tested this using stetho's sample app.

There is no real option to auto open dev tools as far as I can tell, the 
protocol just doesnt support the server (in this case the app) forcing a 
client (chrome) to be created.

**Comment by WalrusCow** [comment]
Yes, my mistake - the breakpoint isn't necessary. You can close this now if you like. Thanks :smile:

**Comment by longinoa** [comment]
Actually this is something that we may want to provide as a feature of stetho in a future release, so I am going to leave it open and add it as an enhancement.

**Comment by jasta** [comment]
I favor a design which exposes this in a similar fashion to `Debug.waitForDebugger`:
```java
Stetho.initialize(...);
Stetho.waitForPeer(); // You add this when you need it...
```

Inside Stetho, this function can be implemented by waiting for the server to fully initialize both dumpapp and WebKit Inspector (conditionally of course based on the `Initializer` passed in).

**Comment by facebook-github-bot-7** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by jasta** [comment]
Bump, we still want to keep this alive.  Anyone willing to tackle a PR?

**Comment by jasta** [comment]
Closing for issue cleanup, still technically relevant but not sufficiently motivated to get it done :)

**Comment by IonutNegru87** [comment]
You can set the device/emulator you are working on to wait for the debugger to be attached and put a break point on your starting code.
At least this is what I'm doing at the moment.
