### ISSUE TITLE
Response tab doesn't show message body correctly

### ISSUE THREAD

**Issue by Woren** [facebook/stetho#169]
Problem is in Chrome - Network tab - and looking at network traffic. When I send more different requests and then want to look to the response message body which surely contains different jsons - but in the "Response" tab I can see only json from the last (or some else) message. Sometimes I can see two / three different jsons out of ten requests (each should be different). Headers tab looks just fine and I can see different informations (content-length etc). I'm using default setup of stetho (1.1.0), okhttp (2.3.0) a chrome (42.0.2311.90 m).
![network](https://cloud.githubusercontent.com/assets/1436458/7294062/51664114-e9aa-11e4-8299-83fb9cc7072d.png)

**Comment by jasta** [comment]
Hmm, that's a very strange error that I've certainly never seen before.  Is this reproducible in some way?

**Comment by Woren** [comment]
Yes, you can test it very easily. I've created very simple sample project (apk in root directory) + here is the link for the MainActivity (everything else is based on Android sample app and default config).

http://pastebin.com/7KjCCqgC
http://www.rziz.net/69s2krnisjs2/StethoTest.zip.html

Try to leave the tab wit Header|Preview|Response|Cookies closed for few first requests then open it, make few requests and then close it again. Requests made with this tab opened are usually correct but in some situations this "trick" doesn't work and you will see only the last request body.
My device is Nexus 5 - 5.0 and I'm using Windows 7 Prof 64bit - just to give you complete informations.

**Comment by jasta** [comment]
I looked at your sample app and it looks like your issue is that you're creating a new OkHttpClient and StethoInterceptor on every request.  This is not only very inefficient (no connection re-use in OkHttpClient) but it also breaks Stetho because it uses an incrementing atomic integer to identify requests.  This is local to StethoInterceptor and not process global, so it will conflate multiple requests with the same request id.  This could be fixed, though I don't think that's the right course of action in this case since there are serious inefficiencies associated with creating multiple OkHttpClient instances.
