### ISSUE TITLE
Activities are added to the Elements tab in reverse order

### ISSUE THREAD

**Issue by jasta** [facebook/stetho#171]
New activities are inserted at the beginning, not the end as would be expected.

**Comment by rickbrew** [comment]
Actually, now that I look at this, I remembered that it's intentional. I wanted new activities to go to the *top* so that they wouldn't just fall to the bottom. I would expect the newest activity to be the most readily accessible one in the Elements UI, and this provides for that.

Now if only I could get it to auto-expand the node too ...
