### ISSUE TITLE
PRAGMA commands not returning values

### ISSUE THREAD

**Issue by teresa-murphy-skvorzova** [facebook/stetho#214]
Hello, I'm wondering if this has something to do with my device (does it have to be rooted?), as any commands to see table schemas are not working for me. Can you advise, please? 

Many thanks.

**Comment by jasta** [comment]
That's due to this logic: https://github.com/facebook/stetho/blob/d39e459ca8e8b6aedfb07df5bb3d9aa5b361f852/stetho/src/main/java/com/facebook/stetho/inspector/database/DatabasePeerManager.java#L153

We wanted to err on the side of caution without sufficient testing in this area.  This is an extremely important use case however so we should definitely get that patched.

**Comment by teresa-murphy-skvorzova** [comment]
Hi - thanks very much for the reply and the explanation. As I have tried several variants of raw queries (but will try some more), could you confirm whether or not it is possible to get table schema information through Stetho at this time? 
Thanks again.

**Comment by jasta** [comment]
select * limit 1 basically. Not an awesome option admittedly, I'll look at
making pragma work properly.
