### ISSUE TITLE
Observe multiple-module project

### ISSUE THREAD

**Issue by ChristofBuechi** [facebook/stetho#230]
Is there a way to observe a project with multiple modules ? I tried a lot with adding a separate application-file because the other module has a different Manifest, root-application file and build.gradle. Is there a way to get this messages also ? I only get network calls listed from the primary project.
Thank you

**Comment by jasta** [comment]
Stetho works properly in a gradle configuration with multiple modules.  Stetho operates on a per-process basis and has little if anything to do with gradle's module configuration.  The problem you're likely running into here is simply a matter of your modules not connected with each other at runtime how you assume they should.  For instance, Stetho must intercept all network traffic in your app in order to show it; it's possible some of your modules don't go through the same centralized network stack as your main module.  This would be a logic bug within your code.

To confirm, use a debugger or simple print debugging to verify that the instance of your network stack being used is indeed the same from one module to the next and that Stetho's interception is wired up in both using a debugger.  I suspect you will find that it is not.
