### ISSUE TITLE
DIfferent dependency for debug and release version without implementing the logic in own project

### ISSUE THREAD

**Issue by gabrielemariotti** [facebook/stetho#232]
It would be nice to have the possibility to manage different dependency in debug and release version, **without implementing the logic in own project**. Usually in a dev tool like this, is not a good practice to include the code in the release version.

Something like this:

```
dependencies {
   debugCompile 'com.facebook.stetho:stetho:1.1.1
   releaseCompile com.facebook.stetho:stetho-no-op:1.1.1'
 }
```

Then in the `Application` class:

``` java
public class ExampleApplication extends Application {

  @Override public void onCreate() {
    super.onCreate();
    Stetho.install(this);
  }
}
```

You can find a similar behaviour in another popular dev-tool like [LeakCanary](https://github.com/square/leakcanary)

Currently a way to achieve it is 

dependencies {
   debugCompile 'com.facebook.stetho:stetho:1.1.1
 }

Then in the Application:

``` java
public class ExampleApplication extends Application {

  @Override public void onCreate() {
    super.onCreate();
    StethoUtils.install(this);
  }
}
```

Finally you should provide different version of `StethoUtils` for the different debug and release versions. It works but the logic is inside all projects instead of the library.

**Comment by jasta** [comment]
We originally pursued this in the early days and ran into a lot of uncomfortable gotchas, though some of those we've had to solve regardless for other reasons.  The first issue was network inspection but we now have a nice solution in `stetho-urlconnection` which lets you ship that jar indepedent of the stetho core (so your release runtime has stetho-urlconnection but it's inert/dead and likely mostly stripped out by proguard).

We have a problem with configuration as well since we tried to make it possible to customize/configure Stetho quite a bit using the `Stetho.initialize` API.  In hindsight however it should be possible to integrate conveniently when you don't need configuration; when you do, you must go through the heavy lifting to make it work.  This is probably a reasonable compromise for most of our users out there.

I'm very willing to entertain this but may not have cycles myself to pursue it soon.  PRs welcome and I think your initial suggestion of a no-op module is the right approach.  FWIW, I favor calling it `stetho-shim` with an API like:

```java
StethoShim.installWithDefaults(this);
```

Might also be worth exploring a simpler `Stetho.initialize` API based on some feedback we've received around both the complexity of the default set up and the awkwardness of customization (it is apparently solving neither case well and that should be addressed).

**Comment by cemo** [comment]
+1

**Comment by sibeliusseraphini** [comment]
[LeakCanary](https://github.com/square/leakcanary) has the no-op options

**Comment by jasta** [comment]
This has been discussed many times before (#16, #263, #322, ...).  The reason this isn't straight forward is because Stetho, unlike LeakCanary, has many configurable options that developers select and so a no-op version for convenience would not be able to offer any of those options without a more sophisticated stub pruning build step (a la android.jar).  This is all possible, but not trivial.

The naive solution would be to offer only `Stetho.initializeWithDefaults(this)` using the no-op stub and then forcing more complex configuration to use the current manifest-based solution (discussed here: http://www.littlerobots.nl/blog/stetho-for-android-debug-builds-only/ and also now added to the Stetho FAQ: https://github.com/facebook/stetho/wiki/FAQ#how-can-i-include-stetho-only-in-release-builds).  This solution is attractive as it would be simple and useful for the vast majority of Stetho users but unfortunately it makes it much more cumbersome to configure Stetho after a deployments already been made so as to discourage customization.  As I think about this a little bit more though perhaps that is the right compromise after all given that customization would add additional dependencies you probably don't want in your release builds as well and this should be your forcing function to divide your app more cleanly between debug and release.

If anyone was interested in working on this I'd happily accept a PR to do it, but I don't have the cycles myself and will be out on extended leave starting at the end of June.
