### ISSUE TITLE
"too many open files" due to several open sockets

### ISSUE THREAD

**Issue by glureau** [facebook/stetho#308]
When chrome://inspect is open, Stetho is opening around 2 new sockets by second without releasing the previous ones. (You can see it easily with lsof.)
After a while, it leads to a "too many open files" issues and the app cannot work properly (network/database errors).

Experienced on Android 4.4.2 P93G, doesn't appear on 4.2.2 neither on Samsung SM-T210 Android 4.4.2.

**Comment by jasta** [comment]
I've seen this bug myself but it repros only on some devices.  I'm fairly confident from inspecting our HTTP server code that we are indeed closing the sockets correctly under nominal circumstances, so I suspect that it is likely an issue with the device manufacturer modifying something they should not have.

That said, we also have recently rewritten our HTTP server implementation to not depend on Apache and this may warrant a renewed look at the problem to see if we can't figure out _exactly_ why this occurs.  It's almost assuredly specific to Samsung however since, well, you know...Samsung is the worst :)

**Comment by jasta** [comment]
See #288 for our new HTTP server implementation, which I am going to work on finishing up this week.

**Comment by jasta** [comment]
@glureau would you be willing to retest on a different, non-Samsung device to confirm my suspicion?  I can say with confidence the issue does not repro on my Nexus 5X or Moto X.

**Comment by glureau** [comment]
Yes I will retry on my devices. Have you already a packaged version?

**Comment by jasta** [comment]
@glureau no sorry, you'd have to build yourself.

**Comment by babyrjw** [comment]
is this problem resolved? I got this exception when debugging my app on android simulator by stetho 1.3.1

**Comment by jasta** [comment]
Presumed fixed by #288

**Comment by jasta** [comment]
If anyone is still running into this issue, please produce a dump of /proc/<yourpid>/fd by doing:

adb shell ps | grep yourapp
# Note the pid
adb shell ls -l /proc/<pid>/fd > fds.txt

**Comment by cazador4** [comment]
Same problem here.
I could reproduce this with this emulator >>
<img width="1159" alt="avd" src="https://cloud.githubusercontent.com/assets/867465/23265484/81af91b0-f9c3-11e6-803d-1d8f87328898.png">

[fds.txt](https://github.com/facebook/stetho/files/796895/fds.txt)

**Comment by rifatdover** [comment]
I can reproduce it with Emulator API 19 too.

**Comment by leoacevedo** [comment]
Same issue here, Nexus One API 19 emulator.

This ticket should be reopened.

[fds.txt](https://github.com/facebook/stetho/files/2387073/fds.txt)
