### ISSUE TITLE
SQLiteDatabase => long , precision lost [bug]

### ISSUE THREAD

**Issue by Gohan** [facebook/stetho#310]
the column type is "Integer", whithout stetho, I can add:
Long.MIN_VALUE
Long.MIN_VALUE+1
Long.MIN_VALUE+2
Long.MIN_VALUE+3
as the column value.

query these values works too.

but after view with stetho
`select * from table where columnvalue < 0`

all the values become -9223372036854776000 which is exceed the Long value.
my android app query values all becomes Long.MIN_VALUE

![image](https://cloud.githubusercontent.com/assets/212567/11419992/00a71cf0-9466-11e5-8e5e-341082ce59b6.png)

**Comment by jasta** [comment]
This is...wut?  I confirmed this bug does indeed exist but amazingly appears to be in Chrome DevTools itself.  I believe that I technically can work around this by converting to string values inside of Stetho since it would appear that Chrome doesn't actually care about column types in any way .

FWIW, I reproduced this in a simple test table and issued `select * from test` with some extra Stetho debug on which printed the raw message sent to Chrome:

    I/System.out( 3775): {"id":38,"result":{"columnNames":["foo","bar"],"values":[-9223372036854775808,-2147483648,-2147483649,-2147483648,-9223372036854775807,-2147483648,-9223372036854775806,-2147483648,-9223372036854770000,-2147483648]}}

Note values like -9223372036854775808 which showed in the UI per your bug report as -9223372036854776000.  Bizarre...
