### ISSUE TITLE
consider no-op release version for method count limit?

### ISSUE THREAD

**Issue by hamberluo** [facebook/stetho#322]

**Comment by jasta** [comment]
The stetho-sample app shows how you can strip Stetho from your release builds, and this stackoverflow post highlights the issue a little more clearly: http://stackoverflow.com/a/30172663/1041385

While we would like to have a stetho-noop artifact available, it is a little trickier than that in practice because the public API for Stetho is much larger than other libraries that offer similar features (for instance, LeakCanary).  See #263.

**Comment by hzsweers** [comment]
@jasta would you consider leaving an issue about this open with the label `help wanted`? If you want it and someone has a good implementation idea, it would be nice to make it clear you'd be open to it (judging solely from the "we would like to have a stetho-noop artifact available" comment above).

**Comment by jasta** [comment]
I'd prefer not to have an open issue to track something like this but we might be able to move it to the FAQ or its own separate section on the wiki and explain that we'd like a solution but it needs to be considered maintainable for it to be viable.
