### ISSUE TITLE
how do I inspect library module

### ISSUE THREAD

**Issue by osemen-remit** [facebook/stetho#351]
I have a project with two modules. One for app itself and another for splitting some functionality in library module. Library is initialised with the context from application. I set-up stetho with this context but I can't see anything in chrome dev tools. I mean I can't even choose my app. I suspect it is because they have different packages (let's say `com.example.app` and `com.example.lib`).

Is it possible to inspect my library module with stetho ? How do I set it up properly ?
Thanks!

**Comment by jasta** [comment]
Stetho works at the app level (specifically at the process level).  Your problem is likely unrelated to the premise of this question.  It seems like you are simply not initializing Stetho in your app's Application#onCreate.  Try putting a Log statement in Application#onCreate to ensure you have correctly set it up to run when the app starts.
