### ISSUE TITLE
Can only load databases from standard database location

### ISSUE THREAD

**Issue by dalewking** [facebook/stetho#376]
Issue #91 added the ability to specify database files in arbitrary locations not just in the standard location for databases that the context knows about. You can specify your own DatabaseFilesProvider to specify a list of database files, but commit 7a27fc7e9557c155c7103daa4a38060332ced182 broke this support. The problem is this code in SqliteDatabaseDriver.getDatabaseNames():

      for (File database : tidiedList) {
        String name = database.getName();
        mDatabases.add(name);
      }

This code throws away the path information so all you have is the file name and then when you ask the context to open it, it tries to open it from the standard database directory.

**Comment by dalewking** [comment]
Any updates?

**Comment by jasta** [comment]
Partially addressed this by merging #367, and formally fixed in #392.

**Comment by jasta** [comment]
...and thank you for your patience on this issue!

**Comment by dalewking** [comment]
Waiting patiently for net release to try it

**Comment by dalewking** [comment]
Still waiting on this to be released

**Comment by jasta** [comment]
@dalewking updated the PR in #392, would you mind verifying that this addresses your issue by pulling the branch (`git checkout -b databaseid-mapping && git pull https://github.com/jasta/stetho.git databaseid-mapping && ./gradlew installArchives`).  If it works as you expect, I'll go ahead and merge and it'll be in the next release (which is coming soon due to other changes we're working on)

**Comment by dalewking** [comment]
I believe I evaluated that PR when it came out and it worked correctly but I cannot say for sure. Unfortunately, I no longer work for that same company and do not have a good way to test it.
