### ISSUE TITLE
can't work in chrome://inspect in opera browser

### ISSUE THREAD

**Issue by zhou-jian** [facebook/stetho#377]
It works fine with chrome, but doesn't work with Opera.

As Opera is also based on chrome, it also has the same 'chrome://inspect' page but cannot see stetho. I wonder if it is something wrong with stetho or something wrong with Opera.

**Comment by jasta** [comment]
We depend on the chrome developer tools client to work, this implies the Chrome browser though not necessarily.  You would never be able to use chrome://inspect, but you could download the client code (HTML and JS, hosted by Google/Chrome) and use it to point to your Stetho server on your phone.  This is the main approach that the PonyDebugger team uses for iOS as they are required to host a local proxy since chrome://inspect doesn't know about iOS devices.
