### ISSUE TITLE
Some Chrome debugging clients may fail

### ISSUE THREAD

**Issue by cpetrov** [facebook/stetho#403]
The _/json_ service provided by the `stetho_com.<...>_devtools_remote` socket returns a JSON payload with a property _webSocketDebuggerUrl_ with value `ws:///inspector`. The missing host part makes tools like the VS Code Chrome debugger (https://github.com/Microsoft/vscode-chrome-debug) fail, as they use the web socket URL provided by the _/json_ service to connect to.

**Background information:**
Using `adb forward` allows one to forward the socket of the Chrome debug target to a port of the client, e.g.:

`adb forward tcp:9222 localabstract:stetho_<...>_devtools_remote`

Then the socket will be accessible on `ws://localhost:9222/inspector` on the client.

Chrome as a debug target (`adb forward tcp:9222 localabstract:chrome_devtools_remote`) returns valid _webSocketDebuggerUrl_s for its pages in the _/json_ service response, e.g.: `ws://localhost:9222/devtools/page/5489`.

**Possible solution:**
After inspection of Chromium's source code, I found out that it simply passes the host part of the request to the _/json_ service through as host part of the `ws://.../` _webSocketDebuggerUrl_ sent back in the JSON response: 
https://cs.chromium.org/chromium/src/components/devtools_http_handler/devtools_http_handler.cc?q=webSocketDebuggerUrl&sq=package:chromium&dr=C&l=927
https://cs.chromium.org/chromium/src/components/devtools_http_handler/devtools_http_handler.cc?sq=package:chromium&dr=C&rcl=1467112798&l=578

Do you think it can also be implemented this way for Stetho?

**Comment by longinoa** [comment]
We didnt really anticipate using stetho outside of chrome. Its an interesting idea, what does VS Code Chrome debugger provide?

@jasta is out for a few more months and he is the one who knows the server code the best. If you want to send a PR for a POC we may be able to iterate on it, but I wont be able to do this.

**Comment by auchenberg** [comment]
Just pitching here as I'm the PM on [vscode-chrome-debug](https://github.com/Microsoft/vscode-chrome-debug). Our debugger allows script-debugging from within VS Code, so you can debug Chrome directly from our editor. See more https://code.visualstudio.com/blogs/2016/02/23/introducing-chrome-debugger-for-vs-code

Since you have embraced the Chrome Debugger Protocol for Stetho, it be wonderful if you also could implement the HTTP JSON endpoint fully, as it' just by Chrome, Us and other to detect debuggable targets. Adding Stetho support to our Chrome debugger isn't a priority, but the community are more than welcome to build one on top of [vscode-chrome-debug-core](https://github.com/Microsoft/vscode-chrome-debug-core)

**Comment by maks** [comment]
I don't think there is much point to doing this right now, as VSC only supports code debugging which is one specific part of the chrome remote debugging protocol that Stetho currently does not appear to support.
