### ISSUE TITLE
Console Logging

### ISSUE THREAD

**Issue by kevelbreh** [facebook/stetho#41]
Is there an example or some functionality to do with redirecting logging to the chrome console instead of to logcat or wherever?

If not, lets get something like this implemented?

**Comment by kevelbreh** [comment]
I did a dirty hack to get logging functionality (i used Timber by Jake Wharton).

It appears that extending Console was a problem.  I can only assume that the classname is being used to hookup the class and methods to chrome's handles.  I recommend perhaps using a class annotation to allow for multiple handlers for each of chromes handles.

Here is a little hack example in case anyone else runs into this: [StethoTree](https://gist.github.com/kevelbreh/e93c09c6b5af3339a3cb)

**Comment by jasta** [comment]
There is a pretty straight forward way to make this work using `ChromePeerManager` and hacking Stetho itself just a little bit (patches welcome *grin*).  Specifically, something like:
```java
public class Console ... {
  private final ConsolePeerManager mConsolePeerManager = ConsolePeerManager.getInstance();

  @ChromeDevtoolsMethod
  public void enable(...) {
    mConsolePeerManager.addPeer(peer);
  }
}

public final class ConsolePeerManager extends ChromePeerManager { ... }
```java

With that change, you can now track all peers that are aware of console updates and can dispatch to them easily using `CLog`:
```java
CLog.writeToConsole(ConsolePeerManager.getInstance(), ...);
```

We wanted to encapsulate this for you, allowing for `CLog` itself to guess `ConsolePeerManager.getInstnace()` by default as well so that callers could just invoke:
```java
CLog.writeToConsole(MessageLevel.WARNING, MessageSource.NETWORK, "foo");
```
