### ISSUE TITLE
Console tags often blank

### ISSUE THREAD

**Issue by uchennafokoye** [facebook/stetho#413]
I am having trouble with the inspect element portion. I am able to see the button 'inspect' on devices page on chrome, but when I click inspect it takes me to another window, with just one html-looking tag. The tag is empty and there is no hierarchy. I have had about two to three instances where I did see the hierarchy as shown in the demo, but every once in a while, when I rerun the app, I see only one empty html-looking tag. 

I usually place Stetho.initializeWithDefaults(this) in the first main activity that would run the app. Is there something else we should be doing?

**Comment by TeunKooijman** [comment]
This happens when you don't call the `Stetho.initializeWithDefaults(this)` call from the onCreate of your application class. So to fix this, create a `BaseApplication` class that extends `Application` and override the onCreate method, placing the call after the super call. Then add `android:name="com.path.to.base.application.BaseApplication"` to the `<application>` entry in your manifest file and everything should work as intended.

Hope this helps.
