### ISSUE TITLE
Adb keep disconnecteing if chrome://inspect tab is open 

### ISSUE THREAD

**Issue by stepango** [facebook/stetho#441]
Stetho cause following error when chrome://inspect tab is open 
adb E   661  9881 usb_osx.cpp:331] Could not open interface: e00002c5
adb E   661  9881 usb_osx.cpp:265] Could not find device interface

more details here http://stackoverflow.com/questions/35650024/macbook-adb-cannot-open-interface

Still reproducible with v1.4.1

**Comment by longinoa** [comment]
Check your version of chrome.

This has nothing to do with stetho but is more the fact that in some versions of chrome there is a bug where chrome://inspect takes over the adb port rather than sharing it with adb. 

The fix, when this happens, is the same fix as the stack overflow question, close the chrome inspect tab and kill/restart adb - though the best way is to have the right combination of chrome and adb that this doesnt happen on.
