### ISSUE TITLE
ResponseHandlingInputStream reads the rest of the stream on close

### ISSUE THREAD

**Issue by erdemguven** [facebook/stetho#446]
When close method is called ResponseHandlingInputStream loops until it reads the whole stream which can take too long time. Is there a way to disable this or a workaround?

**Comment by longinoa** [comment]
This is needed in order to show the full response. Additionally there are issues when you dont consume the entire response in certain http engines.

**Comment by erdemguven** [comment]
Hmm, so what would you recommend to do, not to wait until >100MB file downloaded when download canceled?  This obviously affects how the app works. Do you think a proper solution implemented (I might develop and send a pull request) or should just fork the project do some hack?

**Comment by ojw28** [comment]
+1. Reading the full response seems fine for loading a web page, but if you're making requests into a huge media file this is pretty problematic.

I think http engines typically consume the full response if the remaining length is below some threshold, so that the socket can be re-used. If the remaining length is greater than the threshold they'll tear down the socket.

If an engine does require that the whole of the response is consumed, that should really be implemented within the engine itself (i.e. in `close` of their own `InputStream` implementation). It doesn't make much sense to rely on every caller correctly draining the `InputStream` when reading. Can you point to a concrete example of an http engine that fails to do this and does require the caller to consume the response in full? A source code link would be cool; if it's an open source engine ;).

**Comment by longinoa** [comment]
@ojw28  you are correct, the issues I was speaking about are directly around socket reuse. The fact that we install this is because internally we noticed engineers not reading all of the response due to some business logic that basically meant they were not going to need everything - even if it was already on the client. By not fully consuming the stream the socket got torn down which caused more issues than just reading it all. This had the additional benefit that, in stetho, we would represent the full response - which prevents developers from being very confused as to why, for example, the json is not complete.

@erdemguven  Would you want to disable on a single request/response or in stetho completely? Disabling completely would be a bit more simple as we could add an option to the constructor of the `StethoInterceptor`. 

Are you using OkHttp? From the documentation it sounds like `Call.cancel()` will cause an `IOException` to occur on the read.

**Comment by erdemguven** [comment]
Having a parameter to disable it completely would be great. I tried Call.cancel() but somehow it breaks all connections after a couple of calls. Also I couldn't find a way to inject that call dynamically as I don't want to do that on the release build.

**Comment by jasta** [comment]
@erdemguven the preferred way to do this is to use something like Call.cancel in okhttp or implement your own cancelation mechanism on top of URLConnection which itself doesn't properly support cancelation.
