### ISSUE TITLE
Please remove synthetic methods

### ISSUE THREAD

**Issue by RiteshChandnani** [facebook/stetho#452]
There’s no true nesting in Java. Hence, any access to private members of outer class from nested class will have to go via a package scoped synthesized method generated by Java to facilitate the call.

More information:
https://realm.io/news/360andev-jake-wharton-java-hidden-costs-android/

**Comment by longinoa** [comment]
@RiteshChandnani this is just for removing the additional methods? Presumably this only affects debug builds as prod builds are usually proguarded, and stetho is likely stripped. 

Im not against this, but dont think it has a ton of value in the core of stetho as its a debugging utility, and perf, while important, is not the primary focus. 

We would take pull requests.

**Comment by RiteshChandnani** [comment]
@longinoa 
I agree with your perspective.

But I am curious to know why would you take pull requests on this?

**Comment by longinoa** [comment]
@RiteshChandnani We love pull requests! I would probably recommend doing a small one so we can see the direction you were thinking before converting the entire code base.

**Comment by jasta** [comment]
@RiteshChandnani you might be interested in another Facebook open source tool called redex which applies a build optimization to remove all synthetic methods.  See http://fbredex.com/ for more information (and there are external plugins that integrate redex nicely with gradle as well).  Removing them at the source level can be fairly intrusive in Java since it can unintentionally widen access and appear to change API contracts unintentionally.  This is why we prefer using redex to do it for the final artifact that goes to our users.

**Comment by RiteshChandnani** [comment]
@jasta Thanks a lot, I was about to publish one more app on Play Store, though I have relaxed visibility of such methods for now but even I would like to have a solution at artifact level. I will go through redex right away. :+1: :+1:
