### ISSUE TITLE
can not debug others but view trees.  Device:Nexus5

### ISSUE THREAD

**Issue by hjmJhon** [facebook/stetho#466]
I have configed following useage.It can show viewtrees,but others does not show anyway!

**Comment by longinoa** [comment]
Can you give more information on what you expect to see?

**Comment by levid1900** [comment]
+1  can't see any other but view tree

**Comment by hjmJhon** [comment]
I want to see database,sharepreference data and so on,but I just see viewtrees!

**Comment by wankey** [comment]
Network also can't see

**Comment by jasta** [comment]
What happens when you click on the network tab?  Does it show the UI but
with no entries? If yes, I suspect you just didn't hook up network
inspection (it's not done by default since Stetho doesn't know what your
network library is).  See the web site for instructions on hooking okhttp
or stetho-sample for HttpURLConnection.

**Comment by wankey** [comment]
I had add StethoInterceptor to the library(https://github.com/jeasonlzy/okhttp-OkGo) which i use, but no entries shown

**Comment by jasta** [comment]
Attach a debugger to the StethoInterceptor​ interceptor and see if it's
even running at all.  I suspect not which means the way you hooked it up
isn't correct somewhere.
