### ISSUE TITLE
Multiple instance of StethoInterceptor and mNextRequestId

### ISSUE THREAD

**Issue by ypresto** [facebook/stetho#468]
`StethoInterceptor` instance can be created multiple times, but it have `mNextRequestId` which should be application-wide unique value (as `NetworkEventReporterImpl` seems require it).

I have two okhttp client: picasso's one with cache and retrofit's one without cache.
Creating `StethoInterceptor` each time I create OkHttpClient instance (i.e. calling `addNetworkInterceptor()`) violates `mNextRequestId` (application-wide) uniqueness.

I think it'd be better to make mNextRequestId singleton which is shared by all kind of interceptors.

**Comment by ypresto** [comment]
Workaround is to share single `StethoInterceptor` instance in each application.
But if you use two or more of {okhttp2, okhttp3, jsonrpc}, it cannot be shared because each interceptor is different class.

**Comment by longinoa** [comment]
@ypresto You should indeed share a `StethoInterceptor` in each application. I am not sure how many applications would use multiple different stacks to send network requests, as such I dont know if it is Stetho's place to add this level of complexity into the provided Interceptors - especially since they are dependent on which network stack each app is using. 

I am going to close this - as I dont think there is much need for it, if you would like to submit a PR to address the issue of keeping a common integer we would be open to looking at it but want to keep the `Interceptor`s simple.
