### ISSUE TITLE
Request fulfilled with cache is not shown (okhttp3)

### ISSUE THREAD

**Issue by ypresto** [facebook/stetho#469]
Cache is treated by CacheInterceptor, which is inserted after interceptors and before network interceptors.
https://github.com/square/okhttp/blob/bffefccf7a9b075b3d2998bbfdf409ca2deadc1a/okhttp/src/main/java/okhttp3/RealCall.java#L170

So Stetho, which is added as network interceptor, cannot show any cached response for now (but it has fromDiskCache() method).
https://github.com/facebook/stetho/blob/36aa5bd356d9cf5893b9424b06a83dda9ec5e44f/stetho-okhttp3/src/main/java/com/facebook/stetho/okhttp3/StethoInterceptor.java#L234

**Comment by longinoa** [comment]
`fromDiskCache` is a required method due to the interface in `Interceptor`. You are correct in that this looks like it will never show up from the cache. This is likely a carryover from the initial implementation which probably did it for completeness rather than just returning false. 

This is specifically added via the network inspector rather than through the application inspector because we want to be more about what is happening on the wire - rather than at the request level. That is to say we want to see request/response even if a redirect (or retry) happens. If you install as an application inspector you do not get that visibility - or it would be much harder with the semantics around `mNextRequestId` and how those are displayed in chrome.

**Comment by jasta** [comment]
So, this is a two part issue: 1) I have no idea if fromDiskCache even works in Stetho, I personally never tested it and just sent it as-is to Chrome in case it "just works".  2) StethoInterceptor as you noticed insufficiently hooks okhttp to detect cache hits and report them as pseudo network traffic.

**Comment by jasta** [comment]
Cleaning up our issue queue, this could be reopened if there's sufficient interest tho.
