### ISSUE TITLE
Add ability to edit View properties

### ISSUE THREAD

**Issue by agrieve** [facebook/stetho#476]
From what I can tell, you can edit text and ids from the main inspector window, but anything on the right-hand side under "styles" or "properties" is not editable.

Is this on the roadmap?

**Comment by longinoa** [comment]
cc @rickbrew We have talked about this, but I dont think it is currently under development by anyone.

We would love a PR.

**Comment by rickbrew** [comment]
This would certainly be useful -- back in the WPF days, I used a tool called Snoop that had this type of capability and it was fantastically useful. Especially for fiddling with various layout properties to remove iterations from the edit-build-run-debug cycle.

I don't believe the Chrome inspector UI gives the ability to edit Properties, and maybe not Styles either. However, attributes -- like the text and ids in the main window on the left -- can certainly be edited. So we should probably start adding more of those so they're editable.

Can you give us a little description or more context on what you'd want to use this for?

**Comment by emilsjolander** [comment]
I'm working on something very similar. Hope to push a PR sometime this or next week to expose this for all views.

**Comment by ankitgoyal1009** [comment]
@emilsjolander have you got a chance to push the PR?

**Comment by jasta** [comment]
I believe this idea was abandoned.  Perhaps it can be resurrected tho :\

**Comment by vickychijwani** [comment]
I see PR #503 (merged) added support for editable style properties. It works for some properties if I right click a DOM element and click "Add Attribute" and add something like `alpha="0.5"`. But for most properties it fails because the corresponding Java setter needs either non-string arguments (like `setTextColor(int)` and `setTextColor(android.graphics.Color)`) or multiple arguments (like `setPadding(int, int, int, int)`). For example, I tried `textColor="FF0000"` and then `textColor="0xFFFF0000"` which failed with:

```
W/stetho: IllegalArgumentException: For input string: "#FF0000"
W/stetho: IllegalArgumentException: For input string: "0xFFFF0000"
```
