### ISSUE TITLE
Network inspection not showing anything

### ISSUE THREAD

**Issue by vrunoa** [facebook/stetho#48]
Hi guys, I was just trying stetho and love the Database inspection. One thing, i'm not seing any files on Network Inspection. I'm guessing because I dont use ```OkHttp```. 

For images i'm actually using a lazy loader library. Should I implement the ```StethoURLConnectionManager``` over this library, right? [https://github.com/Urucas/Android-Universal-Image-Loader](https://github.com/Urucas/Android-Universal-Image-Loader)

**Comment by jasta** [comment]
@vrunoa yes, you will need to apply either `stetho-okhttp` or `stetho-urlconnection` in order to see network traffic.  For `stetho-urlconnection`, see the `stetho-sample` app for a working example of how to do this.  For `Android-Universal-Image-Loader` specifically, you'll probably want to subclass `BaseImageDownloader` and wire up `StethoURLConnectionManager` to your subclass.  Disclaimer: I've not actually done this myself so YMMV :)
