### ISSUE TITLE
Socket.io interceptor

### ISSUE THREAD

**Issue by shvelo** [facebook/stetho#498]
Hello, would it be possible to intercept Socket.io frames from [socket.io-client-java](https://github.com/socketio/socket.io-client-java)?

Does Stetho support Chrome DevTools websocket inspection?

**Comment by jasta** [comment]
Funny you should ask!  I've been noodling this over a lot lately and the only reason we haven't proceeded with the support is because most of our raw socket communication at Facebook involves binary protocols (with binary payloads themselves) so we would need to significantly expand our pretty printing functionality in order to visualize things properly.

That said, I'm very open to laying the groundwork for this early by having websocket (and raw socket) APIs wired up in Stetho since chrome://inspect does indeed support this.  The protocol that Stetho would need to speak (specifically how you'd edit https://github.com/facebook/stetho/blob/master/stetho/src/main/java/com/facebook/stetho/inspector/network/NetworkEventReporterImpl.java) is here:

https://github.com/facebook/stetho/blob/36aa5bd356d9cf5893b9424b06a83dda9ec5e44f/build-tools/protocol.json#L1159

The work needed would be in two parts: 1) modify NetworkEventReporterImpl to have APIs to report websocket/socket activity, and 2) provide `stetho-okhttp`-like hooks for common libraries, like okhttp: https://medium.com/square-corner-blog/web-sockets-now-shipping-in-okhttp-3-5-463a9eec82d1

**Comment by jasta** [comment]
Closing as this really is part of a larger effort that at least deserves a more broad task associated.  If you're interested in helping out by all means you can get started with the early patches!

**Comment by jasta** [comment]
I decided to look into this myself concretely and the amount of effort for (1) above is actually quite low.  I'm tackling it myself for the next version though I'm not looking into solving (2) at all.

**Comment by jasta** [comment]
Ok, my part is done.  Feel free to hook Socket.IO :)

**Comment by jasta** [comment]
BTW, I took a quick look at `okhttp3` and this looks like it could be done quite easily with their WebSocket support.  You would use a stetho-friendly `WebSocketListener`:

```java
    class StethoWebSocketListener implements ... {
      NetworkEventReporter mNetworkEventReporter = NetworkEventReporterImpl.get();
      ...
      void onMessage(...) {
        mNetworkEventReporter.webSocketFrameRecieved(...);
      }
    }

    final class DelegatingWebSocketListener implements ... {
      void addListener(...) { ... }
      void removeListener(...) { ... }
      
      void onMessage(...) {
        for (WebSocketListener listener : mListeners) {
          listener.onMessage(...);
        }
      }
    }
```

Then to wire this up in your app:

```java
    client = new OkHttpClient.Builder().build();
    client.newWebSocket(
        request,
        DelegatingWebSocketListener.from(
            new StethoWebSocketListener(),
            new MyListener()));
```

Now `StethoWebSocketListener` can transparently intercept your messages and report them to `chrome://inspect`.  Meanwhile this solution is very friendly to stripping `StethoWebSocketListener` from release builds by instead of hardcoding the `StethoWebSocketListener` you wrap it in a factory whose implementation differs between release and debug builds:

```java
    class DebuggableWebSocketListenerFactory {
      WebSocketListener create(WebSocketListener listener) { ... }
    }
```
