### ISSUE TITLE
Implement SharedPreferences Inspection

### ISSUE THREAD

**Issue by lynfogeek** [facebook/stetho#50]
SharedPreferences could be inspected via the Local Storage area in the Chrome developer tools.

**Comment by jasta** [comment]
Indeed, I think this can go nicely in the Local Storage section of the Resources tab.  I tried to make this work a month back and it wasn't straight forward due to the relationship between HTTP "origins" and that UI.  In particular, I'd need to pretend that shared prefs files are security origins at the start of inspection which would add a blocking filesystem traversal step and could slow down initial inspect.

I need to just try it and see how bad it is in practice.  If it's slow, we can try something more complex by asynchronously updating the page security origins after we scan for shared prefs files.

**Comment by bryanstern** [comment]
How about having Stetho implement a `SharedPreferences#OnSharedPreferenceChangeListener` instead of inspecting the file directly? This would be handy if you implement your own SharedPreferences and do things like encryption or compression.

**Comment by jasta** [comment]
SharedPreferences are actually sharded on Android.  In other words, there can be more than 1 of them and a correct implementation visualizing them should show all that exist.  There is a "standard" one which is presumed by the `PreferenceManager` but it would be incomplete to treat that as the only one.

That said, the real complexity is in figuring out exactly how security origins relate to the "Local Storage" tab.  I tried a few random thoughts a while back and couldn't get anything meaningful to show up there.  I can try harder, tho :)

**Comment by jasta** [comment]
:)

**Comment by lynfogeek** [comment]
Nice! It was fast!
Can't wait to test :)

**Comment by jasta** [comment]
@lynfogeek 1.0.1 just released with this feature.  Looking forward to feedback!
