### ISSUE TITLE
Unable to load  responses for a few network calls , although they log perfectly in Postman 

### ISSUE THREAD

**Issue by amising** [facebook/stetho#502]
For certain GET , POST calls  in my chrome dev tools show size content as" 0" and status  as "pending", although in my response header i can see 200 ok and content length of  few KB, 
raise on SO while  back http://stackoverflow.com/questions/38867355/stetho-unable-to-show-response-for-few-call-in-chrome-dev-tools .
I also  upgraded  to okhttp 3   and stetho 1.4.2  but still plagued by same  issues.
Attaching  screenshot of one such network call selected
![s1](https://cloud.githubusercontent.com/assets/18699651/23352538/b8253682-fced-11e6-858a-cd46675900b1.JPG)
![s2](https://cloud.githubusercontent.com/assets/18699651/23352539/ba490402-fced-11e6-9df2-f84a7079dfd5.JPG)

**Comment by jasta** [comment]
Hmm, it's possible that something is throwing an exception or otherwise aborting the interceptor flow during another OkHttp interceptor (or perhaps even inside okhttp itself due to something you've hooked or an upstream bug?) and that's causing us to only see the initial request going out but not the reply.  Since you can repro you're in the best possible position to get a little bit of extra debug info for us.  Could you try just attaching a debugger into `StethoInterceptor#intercept` and step through to see what it's doing or if it gets interrupted.

Note that the way Stetho intercepts your network traffic is not at a low level such as sockets, instead it relies on okhttp in this case to report the information and state via okhttp's own Interceptor API.  So basically whatever StethoInterceptor sees is what chrome://inspect will show.
