### ISSUE TITLE
Stetho does not show duplicate request headers

### ISSUE THREAD

**Issue by sausti** [facebook/stetho#531]
Using version 1.5.0, Stetho does not show duplicate request headers when viewing the request or when the request is copied as a curl. It seems that duplicate headers are ignored/displayed as one, which can make debugging hard and or force one to turn to Charles Proxy/upstream logging.

Perhaps there is an option for showing duplicate headers that I am missing?

**Comment by jasta** [comment]
Hmm.  I believe this is a limitation with the JSON formatting of headers in chrome://inspect's protocol which forces us to use JSON keys as header names, such that we would encode { "Foo": "1", "Foo": "2" } and the corresponding JSON parser in chrome would interpret that as Foo => 2 (or maybe Foo => 1, hard to say for sure).  Recent versions of Chrome may have addressed the protocol deficiency and we could check but that's a whole separate project to try to update to the latest chrome :(

**Comment by jasta** [comment]
One quick suggestion: you could actually try modifying the interceptor a bit to detect this case yourself and mangle your headers by adding like "Foo_1", "Foo_2", etc in the header name.  You could do this by just copy/pasting StethoInterceptor and adding the feature yourself then installing that copied version into your app instead of the standard one.  Not an awesome solution I know, but it's a pragmatic way around the issue.
