### ISSUE TITLE
Abnormal Behavior with RecylerView

### ISSUE THREAD

**Issue by ardanees-jatali** [facebook/stetho#539]
I am working on a project that works fine without stetho when i add stetho, the recyclerview is working no more the data added to recyclerview is not visible.

**Comment by jasta** [comment]
Hmm, this doesn't seem very likely that it is Stetho's bug, but more likely a nuanced logic bug in your application.  The way stetho "scrapes" the view hierarchy is by just periodically scanning from the root to all child nodes and then informing chrome://inspect about what it saw.  If chrome://inspect isn't open and connected, stetho basically does nothing and is highly unlikely to affect your program's logic otherwise.
