### ISSUE TITLE
Keep Chrome Tools open after app stops

### ISSUE THREAD

**Issue by jkane001** [facebook/stetho#55]
Hoping there's a way to do this - after a JSON Mapping issue (in my case, using GSON w/ Retrofit), the app force-closes, and immediately the inspection window closes with it. I cannot, therefore, see what the response was, and see what unexpected JSON came back. It would be a huge win to have that ability!

**Comment by jasta** [comment]
You might be able to find it by looking at `adb shell run-as com.yourpackage ls files`.  It writes files like `network-response-body-*` which the system normally cleans up when it doesn't force close.  It will eventually delete them if you inspect again tho.

Unfortunately keeping the window open isn't possible AFAICT because once the socket disconnects the window automatically closes.  The only way I can think of to fix that would be to use a proxy server of some kind so that the connection to the DevTools UI wasn't severed (just the connect to the proxy).

**Comment by jasta** [comment]
We've been considering our own devtools client recorder which automagically creates HAR files and such so that it can be used to instrument runs of the app that are crashing or where problems are happening very early during initialization.  This might be a great compromise for your issue as well.  Thoughts?

**Comment by facebook-github-bot-7** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by jasta** [comment]
Chrome made this change :)

**Comment by jkane001** [comment]
@jasta care to elaborate?
