### ISSUE TITLE
How to set limit of sql rows? 

### ISSUE THREAD

**Issue by maksimsukalov** [facebook/stetho#550]
How to set limit of sql rows?

**Comment by abiemann** [comment]
I've had it with Stetho's limited number of returned rows. On my next project I plan to use https://github.com/amitshekhariitbhu/Android-Debug-Database instead

**Comment by jasta** [comment]
@abiemann sadly we cannot easily work around chrome://inspect's UI limitations and the row limit is fundamentally about that very problem.  That said, the Android-Debug-Database project does look like a reasonable alternative as they're providing their own UI on top of what Stetho can currently do.

As an implementation note, however, Stetho is actually flexible to providing extensible custom UIs such as the one provided by Android-Debug-Database, we just haven't provided that ourselves given the huge amount of effort to maintain all the possible differnet UIs folks could want.  Something that was pluggable and extensible however could go quite far and I'm very interested in community effort around that initiative.

Oh, and be wary of Android-Debug-Database style solutions as they contain severe security issues associated with using TCP to accept arbitrary socket connections to inspect your database.  Just by listening on or connecting to an unprivileged port (1024+) these libraries open up your application to be inspected by malicious apps running on the user's phones, stealing any data that would otherwise be in your app's database like authentication tokens, user sensitive data, etc.  Stetho is not vulnerable to this problem because it uses UNIX domain sockets and verifies that no regular Android app is on the other side of the connection.

**Comment by jasta** [comment]
https://github.com/amitshekhariitbhu/Android-Debug-Database/issues/93 -- I commented on their project about the security issues and also made a request to see if we could use the two projects together somehow.
