### ISSUE TITLE
Database inspection with OrmLite 

### ISSUE THREAD

**Issue by v-ken** [facebook/stetho#554]
Is it possible to use the database inspection tool with OrmLite?
I'm not able to locate the database in the `Web SQL` folder.

**Comment by jasta** [comment]
Yes, see: 
https://github.com/facebook/stetho/blob/master/stetho-sample/src/debug/java/com/facebook/stetho/sample/SampleDebugApplication.java#L67

Specifically, you can provide your own database driver which works with any library you wish, provided it's generally compatible with Stetho's database support.  That said, in your case I think it might be a matter of locating the SQLite database files instead of choosing an entirely unique driver.  For that, also try just passing `databaseFiles` or manually constructing the `SqliteDatabaseDriver` per the javadocs.
