### ISSUE TITLE
Respect "Preserve Log" setting in Network tab of Chrome Dev Tools

### ISSUE THREAD

**Issue by jkane001** [facebook/stetho#56]
There are times when the list of network calls gets replaced by a new set of calls (not 100% sure what causes that, so maybe that's the bug), but checking the "Preserve Logs" checkbox doesn't prevent those items from being removed, as it should.

**Comment by jasta** [comment]
You can click "Clear" explicitly to remove entries, but I'm otherwise not aware of any way to have the entires removed automatically.  Note that due to #13 there may be other weird upstream bugs we don't know about that cause rendering glitches.

As far as preserve logs, I don't think that would help in either case.  That's designed to not clear the network traffic when navigating to another page which is a concept we don't even support currently :)
