### ISSUE TITLE
Migrate BSD + patents license to MIT or Apache v2.0, as done for React

### ISSUE THREAD

**Issue by LouisCAD** [facebook/stetho#568]
Hi Facebook,

Could you consider migrating the license of this project too, as has been [announced](https://code.facebook.com/posts/300798627056246/relicensing-react-jest-flow-and-immutable-js/) and [done](https://github.com/facebook/react/commit/b765fb25ebc6e53bb8de2496d2828d9d01c2774b) to React?

**Comment by jasta** [comment]
I'm checking internally for you.

**Comment by LouisCAD** [comment]
I hope this issue is on the right path. I have an Apache 2.0 licensed library that has Stetho as a dependency of a module, and I guess I'm on the wrong side of the law until Stetho changes its license 😕

**Comment by jasta** [comment]
@LouisCAD disclaimer: IANAL, however, Stetho's license is unusual since if you strip Stetho out of your release builds (which we generally recommend as a reasonable production shipping configuration), then you are not distributing Stetho to your users and therefore the copyright clauses are enacted differently.  I encourage you to look into how copyright is affected by whether or not you are actually distributing the software in question, instead of simply using it as a tool.

That said, I am still looking into this as we evaluate projects on a case by case basis.

**Comment by jasta** [comment]
Good news, the license change has been approved!
