### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by hzsweers** [facebook/stetho#579]
I noticed there's a ton of un-acknowledged outstanding issues and PRs.

**Comment by jasta** [comment]
The project is not abandoned, but it is fair to say it is stable and mature.  It is heavily exercised internally at Facebook on a daily basis by at least a half dozen projects.  That said, I have personally been letting you folks down however and for that I sincerely apologize.  I typically try to go through and cleanup issues at least once per month but have been distracted by a number of personal and professional projects and for that I'm truly sorry.

Toward the end of the year I'll have time to go through and cleanup PRs.

**Comment by hzsweers** [comment]
Stable and mature, but there at 18 PRs open and some fixing KIs. I think it hurts the credibility of the project for external pitches when it gets into the state that it has the last ~6 months. Litho also recently deprecated their stetho support, which adds to the wonder about whether or not it's still maintained. Just my 2c. Looking forward to development picking up again

**Comment by jasta** [comment]
@hzsweers I agree, this isn't an appropriate state for a project still in heavy use within Facebook and externally.  I'll resolve to do better.

As for Litho, there are separate issues at play there.  Litho is a complex abstraction and chrome://inspect's rules don't quite fit as well as we'd hoped.  We don't have a clear solution for the community yet at this time, but it otherwise doesn't suggest Stetho is dead either.
