### ISSUE TITLE
How can I update DevTools version?

### ISSUE THREAD

**Issue by starikan** [facebook/stetho#626]
When I connect with devtools provided by Stetho it`s show me very old version. How can I upgrade version of devtools?

**Comment by jasta** [comment]
This can be done (in theory) by editing Stetho itself and selecting a newer version.  However, many things would be expected to break and we'd need to try to get a sense of the total scope before we could invest the time in upgrading.  It's a scary big project, but we haven't tried in over a year so it's possible things could have actually gotten easier due to more compatible changes in Chrome devtools themselves.

To give it a try, edit this file: https://github.com/facebook/stetho/blob/master/stetho/src/main/java/com/facebook/stetho/inspector/ChromeDiscoveryHandler.java#L47.  The webkit version corresponds to the devtools version internally and therefore selects which version of the client devtools you want to be using.  That version is fetched from Google's servers, which they have graciously chosen to serve extremely old versions seemingly forever :)
