### ISSUE TITLE
Does stetho support okhttp with websocket?

### ISSUE THREAD

**Issue by b95505017** [facebook/stetho#76]
Cause okhttp will support websocket fully in the future, ex. this
https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/com/squareup/okhttp/recipes/WebSocketEcho.java

If I add stetho to inspect this, app will crash.
Chrome dev tool could monitor websocket activity, does stetho support it as well?

Thanks.

**Comment by jasta** [comment]
Can you post the stack trace?  Supporting this really depends on how OkHttp's interceptors system works with respect to WebSocket traffic.  We also don't have API support in stetho's `NetworkEventReporter` however that can be easily added.

Note however that the DevTools' WebSocket inspection is fairly limited.  In particular, binary frames are not visualized so that it can be difficult in practice to use this feature with efficiently designed websocket protocols.
