### ISSUE TITLE
Support passing android serial as parameter - improvement for dumpapp script 

### ISSUE THREAD

**Issue by jhuska** [facebook/stetho#79]
Would not be more handy to have dumpapp script more user friendly for running Stetho on multiple devices simultaneously ?

Currently the Android serial is retrieved as a system variable. Can the script be altered to take Android serial as a parameter with fallback to system variable ?

I would send a pull request if you consider this as useful.

**Comment by jasta** [comment]
We wanted to avoid this in `dumpapp` because currently most of the option parsing happens on the server itself (`-p` is the only option parsed by the client).  That said, we could add more by making the parser a little more sophisticated (remember, we have to actually remove the options parsed locally before they're sent to the Stetho server).

I'd be happy to accept a diff which adds `-s` / `--serial` but do note that `ANDROID_SERIAL=foo ./scripts/dumpapp -p ... blabla` would function the same without the same side effects in the shell that `export` causes.  This is how we internally use `dumpapp` for automation.

**Comment by brennantaylor** [comment]
Maybe the issue is just that ANDROID_SERIAL isn't documented.

**Comment by jhuska** [comment]
Thanks for your insight. I have not realized that ``ANDROID_SERIAL=foo`` would be sufficient in automation. That would be sufficient for me.

**Comment by SharanuPatted** [comment]
@jasta @jhuska : Is this fixed as part of latest code?
